name: Run Tests

on:
  push:
    paths:
      - '.github/workflows/ci-test.yml'
      - 'src/**'
      - 'tests/**'
  pull_request:
    paths:
      - '.github/workflows/ci-test.yml'
      - 'src/**'
      - 'tests/**'

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python: [3.7, 3.8, 3.9]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Mypy
        run: |
          pip install mypy
          mypy src/inka

      - name: Test with pytest
        run: |
          pip install .
          mkdir -p ~/.local/share/Anki2/test/collection.media/
          pytest --cov=inka --cov-report=xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          flags: unittests
          name: GitHub
